
<div class="sidebar">
  <div class="sidebar-dropdown"><a href="#">Navigation</a></div>
    <ul id="nav">

      <li id="main-index" class="has_sub main" value="index/index">
        <a href="#" ><i class="fa fa-home"></i> 
          Geral  
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
      </li>  

      <li id="main-customer" class="has_sub main" value="customer/index">
        <a href="#"><i class="fa fa-bar-chart-o"></i> 
          Clientes  
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
      </li>  

      <li id="main-tma" class="has_sub">
        <a href="#"><i class="fa fa-bar-chart-o"></i> 
          TMA  
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
        <ul>
          <li > <a href="../tma/index" >Tickets</a></li>
          <li > <a href="../tma/queue" >Fila</a></li>
          <li><a href="tmaanalistapage" class="btn disabled " role="button">Tratamento por analista</a></li>
        </ul>
      </li> 

      <li id="main-gestao" class="has_sub" value="gestao/index">
        <a href="#" class="btn disabled " role="button" >
          <i class="fa fa-bar-chart-o "></i>Gestão
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
      </li>

    </ul>
</div>  

<script type="text/javascript">

  $('.main').click(function(){

    var url = $(this).attr('value');
    $(location).attr('href', '../' + url);
  });
</script>