        
<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="volumeTipoMes"></div>
      </div>
    </div>
  </div>
</div>

<?php 
    if ( 9 != NULL ):
?>   

<script type="text/javascript">

    $('#volumeTipoMes').highcharts({
         chart: {
            type: 'column'
        },
        title: {
            text: 'Volume de tickets fechados x Mês'
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            categories: [ <?php echo $this->legend; ?> ]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Volume'
            }
        },
        tooltip: {
            headerFormat: '<b><span style="font-size:12px">Mês: {point.key}</span> </b> <br>',
            pointFormat: '<span style="color:{series.color}">{series.name}: ' +
                '<b>{point.y:1f} </span></b><br>',
            footerFormat: '',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {
                                    var firstDate = $('#firstDate').val() + ' 00:00:00';
                                    var lastDate = $('#lastDate').val() + ' 23:59:59';
                                    var type = $('#type').val();
                                    var where = "status = 'closed successful' AND to_char(to_timestamp (EXTRACT(month from closetime)::text, 'MM'), 'TMmon') || '/' || EXTRACT(YEAR from closetime) = '" + this.category + "' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + "'";
                                                 
                                    $.post( "ticketlist", 
                                            { where: where,
                                              type: type } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                    });                                           
                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black, 0 0 3px black'
                    }
                }
            }
        },
        series: [ {
                    name: 'Defeito',
                    data: [<?php echo $this->Defeito; ?>]
                }, {
                    name: 'Solicitação',
                    data: [<?php echo $this->Solicitação; ?>]
                }, {
                    name: 'Reclamação',
                    data: [<?php echo $this->Reclamação; ?>]
                },{
                    name: 'Informação',
                    data: [<?php echo $this->Informação; ?>]
                },{
                    name: 'Alteração',
                    data: [<?php echo $this->Alteração; ?>]
                },{
                    name: 'Desconexão',
                    data: [<?php echo $this->Desconexão; ?>]
                },{
                    name: 'Cobrança',
                    data: [<?php echo $this->Cobrança; ?>]
                }

            ]
    });
  
</script>

<?php 
    else :
?>
<script type="text/javascript">
        
        $('#volumeTipoMes').html('<h3 align="center"><i>Não há dados para exibir o gráfico "Volume de tickets fechados x Mês". Por favor, altere os filtros.</i></h3>');

</script>
<?php
    endif
?>