<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="volumeCidade"></div>
      </div>
    </div>
  </div>
</div>
        
<?php 
    if ( $this->values != 0 ):
?>  

<script type="text/javascript">

    $('#volumeCidade').highcharts({
      chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Volume por cidade'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.y} - {point.percentage:.1f}%</b>'
        },
        plotOptions: {
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {
                                    var firstDate = $('#firstDate').val() + ' 00:00:00';
                                    var lastDate = $('#lastDate').val() + ' 23:59:59';
                                    var type = $('#type').val();
                                    var city = this.name;
                                    var filter = [];
                                        filter['CTA'] = "' AND SUBSTRING(customer from 1 for 3) IN('CTA','PNI','ATT','BCU','AUC') ";
                                        filter['OCO'] = "' AND SUBSTRING(customer from 1 for 3) IN('OCO','BRE')";
                                        filter['MUA'] = "' AND SUBSTRING(customer from 1 for 3) IN('MUA')";
                                        filter['SJC'] = "' AND SUBSTRING(customer from 1 for 3) IN('SJC')";

                                    var where = "status = 'closed successful' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + filter[city] ;

                                    $.post( "ticketlist", 
                                            { where: where,
                                              type: type } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                    });                                           

                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
            pie: {
                showInLegend: true,
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.y} - {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Volume',
            data: [
                <?php echo $this->valuesGraphCTA . $this->valuesGraphOCO . $this->valuesGraphMUA . $this->valuesGraphSJC; ?>
            ]
        }]
    });
  
</script>

<?php 
    else :
?>
<script type="text/javascript">
        
        $('#volumeCidade').html('<h3 align="center"><i>Não há dados para exibir o gráfico "Volume por cidade". Por favor, altere os filtros.</i></h3>');

</script>
<?php
    endif
?>