        
<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
        <a href="#" class="wclose"><i class="fa fa-times"></i></a>
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="volumeTicket"></div>
      </div>
    </div>
  </div>
</div>

<?php 
    if ( $this->openValues != 0 ):
?>   

<script type="text/javascript">

    $('#volumeTicket').highcharts({
         chart: {
            type: 'column'
        },
        title: {
            text: 'Volume de tickets x Mês'
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            categories: [ <?php echo $this->openLegend; ?> ]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Volume'
            }
        },
        tooltip: {
            headerFormat: '<b><span style="font-size:12px">Mês: {point.key}</span> </b> <br>',
            pointFormat: '<span style="color:{series.color}">{series.name}: ' +
                '<b>{point.y:1f} </span></b><br>',
            footerFormat: '',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {
                                    var firstDate = $('#firstDate').val();
                                    var lastDate = $('#lastDate').val();
                                    if( this.series.name == 'Ticket fechados'){
                                        var where = "status = 'closed successful' AND to_char(to_timestamp (EXTRACT(month from closetime)::text, 'MM'), 'TMmon') || '/' || EXTRACT(YEAR from closetime) = '" + this.category + "' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + "'";
                                    }
                                    else{
                                        var where = "to_char(to_timestamp (EXTRACT(month from opentime)::text, 'MM'), 'TMmon') || '/' || EXTRACT(YEAR from opentime) = '" + this.category + "' AND opentime >= '" + firstDate + "' AND opentime <= '" + lastDate + "'"; 
                                    }
                                                 
                                    $.post( "ticketlist", 
                                            { where: where } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                    });                                           
                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Ticket fechados',
            data: [ <?php echo $this->closeValues; ?> ],
            dataLabels: {
                    enabled: true,
                    rotation: 0,
                    align: 'center',
                    x: 0,
                    y: 0,
                    style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif',
                        fontWeight: 'bold',
                        
                    }
            }

        },
        {
            name: 'Ticket abertos',
            data: [ <?php echo $this->openValues; ?> ],
            dataLabels: {
                    enabled: true,
                    rotation: 0,
                    align: 'center',
                    x: 0,
                    y: 0,
                    style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif',
                        fontWeight: 'bold',
                        
                    }
            }

        }]
    });
  
</script>

<?php 
    else :
?>
<script type="text/javascript">
        
        $('#volumeTicket').html('<h3 align="center"><i>Não há dados para exibir o gráfico "Volume de tickets x Mês". Por favor, altere os filtros.</i></h3>');

</script>
<?php
    endif
?>