

<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
        <a href="#" class="wclose"><i class="fa fa-times"></i></a>
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="timeAfeta"></div>
      </div>
    </div>
  </div>
</div>
        
<?php 
    if ( $this->values != 0 ):
?>   

<script type="text/javascript">

    $('#timeAfeta').highcharts({
      chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Tempo dos tickets acionados - Afeta serviço'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.y}</b>'
        },
        xAxis: {
            categories: [
            ],
            labels: {
                rotation: 0,                
            }
        },
        plotOptions: {
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {
                                    var firstDate = $('#firstDate').val();
                                    var lastDate = $('#lastDate').val();
                                    var timeArr = { 'Até 4 horas': 'totaltime > 0 AND totaltime <= 14400' , 
                                                    'De 4 a 8 horas': 'totaltime > 14400 AND totaltime <= 28800', 
                                                    'De 8 a 12 horas': 'totaltime > 28800 AND totaltime <= 43200', 
                                                    'Acima de 12 horas': 'totaltime > 43200'};

                                    var where = "type = 'Incident' AND causa = 'Fibra óptica' AND service_affected='Sim' AND ts = 'closed successful' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + "' AND " + timeArr[this.name] ;
                                    $.post( "ticketlist", 
                                            { where: where } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                    });                                           

                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
            pie: {
                showInLegend: true,
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.y} - {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Volume',
            data: [
                <?php echo $this->valuesGraph; ?>
            ],
        }]
    });
  
</script>

<?php 
    else :
?>
<script type="text/javascript">
        
        $('#timeAfeta').html('<h3 align="center"><i>Não há dados para exibir o gráfico "Tempo dos tickets acionados - Afeta serviço". Por favor, altere os filtros.</i></h3>');

</script>
<?php
    endif
?>