        
<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
        <a href="#" class="wclose"><i class="fa fa-times"></i></a>
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="volumeMes"></div>
      </div>
    </div>
  </div>
</div>

<?php 
    if ( $this->valuesNotAffected != 0 ):
?>   

<script type="text/javascript">

    $('#volumeMes').highcharts({
         chart: {
            type: 'column'
        },
        title: {
            text: 'Volume de acionamentos de rede externa x Mês'
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            categories: [ <?php echo $this->legend; ?> ]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Volume'
            }
        },
        tooltip: {
            headerFormat: '<b><span style="font-size:12px">Mês: {point.key}</span> </b> <br>',
            pointFormat: '<span style="color:{series.color}">{series.name}: ' +
                '<b>{point.y:1f} </span></b><br>',
            footerFormat: '',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {
                                    var affect = { 
                                        'Afeta Serviço': 'Sim',
                                        'Não Afeta Serviço': 'Não',
                                    }
                                    var firstDate = $('#firstDate').val();
                                    var lastDate = $('#lastDate').val();
                                    var where = "ts = 'closed successful' AND causa='Fibra óptica' AND  type = 'Incident' AND EXTRACT('MONTH' FROM closetime::date) || '/' || EXTRACT('YEAR' FROM closetime::date) = '" + this.category + "' AND service_affected = '" + affect[this.series.name] + "' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + "' ";
                                                 
                                    $.post( "ticketlist", 
                                            { where: where } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                    });                                           
                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            color: '#228B22',
            name: 'Não Afeta Serviço',
            data: [ <?php echo $this->valuesNotAffected; ?> ],
            dataLabels: {
                    enabled: true,
                    rotation: 0,
                    align: 'center',
                    x: 0,
                    y: 0,
                    style: {
                        fontSize: '13px',
                        fontSizentFamily: 'Verdana, sans-serif',
                        fontWeight: 'bold',
                        
                    }
            }

        }, {
            color: '#B22222',
            name: 'Afeta Serviço',
            data: [ <?php echo $this->valuesAffected; ?> ],
            dataLabels: {
                    enabled: true,
                    rotation: 0,
                    align: 'center',
                    x: 0,
                    y: 0,
                    style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif',
                        fontWeight: 'bold',
                        
                    }
            }

        }]
    });
  
</script>

<?php 
    else :
?>
<script type="text/javascript">
        
        $('#volumeMes').html('<h3 align="center"><i>Não há dados para exibir o gráfico "Volume de acionamentos de rede externa x Mês". Por favor, altere os filtros.</i></h3>');

</script>
<?php
    endif
?>