
<div class="sidebar">
  <div class="sidebar-dropdown"><a href="#">Navigation</a></div>
    <ul id="nav">

      <li id="main-index" class="has_sub main" value="index/index">
        <a href="#" ><i class="fa fa-bar-chart-o"></i> 
          Geral  
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
      </li>  

      <li id="main-customer" class="has_sub main" value="acionamento/index">
        <a href="#"><i class="fa fa-bar-chart-o"></i> 
          Acionamentos  
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
      </li>  

      <li id="main-tma" class="has_sub">
        <a href="#"><i class="fa fa-bar-chart-o"></i> 
          TMA  
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
        <ul>
          <li > <a href="../tma/index" >Tickets</a></li>
        </ul>
      </li> 

      <li id="main-rede-externa" class="has_sub main" value="campo/index">
        <a href="#"><i class="fa fa-bar-chart-o"></i> 
          Rede Externa  
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
      </li> 

      <li id="main-gestao" class="has_sub">
        <a href="#"><i class="fa fa-bar-chart-o"></i> 
          Gestão  
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
        <ul>
          <li > <a href="../gestaogeral/index" >Geral</a></li>
          <li class="btn disabled " role="button" > <a href="../gestaoanalista/index" >Analista</a></li>          
        </ul>
      </li> 

      <li id="main-alarmes" class="has_sub" value="alarmes/index">
        <a href="#" class="btn disabled "><i class="fa fa-bar-chart-o "></i> 
          Alarmes AHS
          <span class="pull-right"><i class="fa fa-chevron-right"></i></span>
        </a>
      </li> 

    </ul>
</div>  

<script type="text/javascript">

  $('.main').click(function(){

    var url = $(this).attr('value');
    $(location).attr('href', '../' + url);
  });
</script>