
<!-- Table Page -->
<div class="page-tables ">
  <!-- Table -->
  <div class="table-responsive">
    <table class="table table-striped " cellspacing="0" width="100%" id="data-table" >
      <thead>
        <tr>
          <th>ID</th>
          <th>Tipo</th> 
          <th>Título</th>
          <th>Abertura</th> 
          <th>ID</th>
          <th>Nome do Cliente</th>
          <th>Causa</th>
          <th>Solução</th>
        </tr>
      </thead>
      <tbody style="font-size: 13px;">
        <?php foreach ($ticketList as $ticket) : ?>
        <tr>
            <td>
              <a href="https://10.100.0.42/otrs/index.pl?Action=AgentTicketZoom;TicketID=<?php echo $ticket['id']; ?>" target="_blank">
                <?php echo $ticket['tn']; ?>
              </a>
            </td>
            <td><?php echo $ticket['type'];?></td>   
            <td><?php echo $ticket['title'];?></td>   
            <td><?php echo $ticket['opentime'];?></td>   
            <td><?php echo $ticket['customer'];?></td>  
            <td><?php echo $ticket['customer_name'];?></td>  
            <td><?php echo $ticket['causa'];?></td>  
            <td><?php echo $ticket['solucao'];?></td>     
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    <div class="clearfix"></div>
  </div>
</div>

<!-- JS -->
<script type="text/javascript">
/* Data tables */
  $(document).ready(function() {
    $('#data-table').dataTable({
       "sPaginationType": "full_numbers",

    });
  });
 
</script>
    




