
<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="totalTimeAtendimento"></div>
      </div>
    </div>
  </div>
</div>
        
<?php 
    if ( $this->values != 0 ):
?>      

<script type="text/javascript">

    $('#totalTimeAtendimento').highcharts({
      chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Tempo total dos tickets que não foram acionados o CTC'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.y} - {point.percentage:.1f}%</b>'
        },
        plotOptions: {
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {
                                    var firstDate = $('#firstDate').val();
                                    var lastDate = $('#lastDate').val();
                                    var type = $('#type').val();
                                    var where = "status = 'closed successful' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + "' AND tmatotal = '" + this.name + "' AND (tratamento_tecnico + binario) = 0";
                                    $.post( "ticketlist", 
                                            { where: where,
                                              type: type } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                    });                                           
                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
            pie: {
                showInLegend: true,
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Volume',
            data: [
                <?php echo $this->valuesGraph; ?>
            ]
        }]
    });
  
</script>

<?php 
    else :
?>
<script type="text/javascript">
        
        $('#totalTimeAtendimento').html('<h3 align="center"><i>Não há dados para exibir o gráfico "Tempo total dos tickets que não foram acionados". Por favor, altere os filtros.</i></h3>');

</script>
<?php
    endif
?>


<!-- Scripts -->
  <?php echo $this->headScript()
  ->prependFile($this->basePath() . '/js/dropdown.js')  ; ?>