
<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
        <a href="#" class="wclose"><i class="fa fa-times"></i></a>
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="totalTimeType"></div>
      </div>
    </div>
  </div>
</div>
        

<script type="text/javascript">

    $('#totalTimeType').highcharts({
      chart: {
            type: 'column'
        },
        title: {
            text: 'Tempo total x Tipo '
        },
        xAxis: {
            categories: ['Defeito', 'Solicitação', 'Reclamação', 'Informação', 'Alteração', 'Desconexão', 'Cobrança']
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Volume'
            },
            stackLabels: {
                enabled: true,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: false,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black, 0 0 3px black'
                    }
                }
            },
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {
                                    var firstDate = $('#firstDate').val();
                                    var lastDate = $('#lastDate').val();
                                    var type = $('#type').val();
                                    var tmatotal = " AND tmatotal = '" + this.series.name + "'";
                                    if(this.series.name == 'Até 4 horas'){
                                        var tmatotal = " AND (tmatotal = '" + this.series.name + "' OR tmatotal like 'Fechado%')";
                                    }
                                    var where = "status = 'closed successful' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + "' AND type = '" + this.category + "'" + tmatotal ;
                                    $.post( "ticketlist", 
                                            { where: where,
                                              type: type } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                    });                                           
                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
        },
        series: [{
            name: 'Até 4 horas',
            data: [<?php echo $this->valuesOne; ?>]
        }, {
            name: 'De 4 a 8 horas',
            data: [<?php echo $this->valuesTwo; ?>]
        }, {
            name: 'De 8 a 12 horas',
            data: [<?php echo $this->valuesThree; ?>]
        }, {
            name: 'Acima de 12 horas',
            data: [<?php echo $this->valuesFour; ?>]
        }]
    });
  
</script>
