<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
        <a href="#" class="wclose"><i class="fa fa-times"></i></a>
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="volumeProduto"></div>
      </div>
    </div>
  </div>
</div>
        

<script type="text/javascript">
    

    $('#volumeProduto').highcharts({
      chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Volume por produto'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.y} - {point.percentage:.1f}%</b>'
        },
        plotOptions: {
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {                                    
                                    var firstDate = $('#firstDate').val();
                                    var lastDate = $('#lastDate').val();

                                    var where = "status = 'closed successful' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + "' AND product = '" + this.name + "'";

                                    $.post( "ticketlist", 
                                            { where: where } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                        $('#myModalLabel').html('Lista de Tickets ');     
                                    });                                           
                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
            pie: {
                showInLegend: true,
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.y} - {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Volume',
            data: [
                <?php echo $this->values; ?>
            ]
        }]
    });
  
</script>



