        
<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left"></div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
        <a href="#" class="wclose"><i class="fa fa-times"></i></a>
      </div>  
      <div class="clearfix"></div>
    </div>             
    <div class="widget-content">
      <div class="padd">
        <div id="volumeService"></div>
      </div>
    </div>
  </div>
</div>

<?php 
    if ( $this->values != 0 ):
?>   

<script type="text/javascript">

    var customerName = {<?php echo $this->customerName ?>};
    $('#volumeService').highcharts({
         chart: {
            type: 'column'
        },
        title: {
            text: 'Top 10 - Volume de tickets por serviços'
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            categories: [ <?php echo $this->legend; ?> ]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Volume'
            }
        },
        tooltip: {
            formatter: function () {
                var label = '<b>' + customerName[this.x] + '</b>';

                $.each(this.points, function () {
                    label += '<br/>' + this.series.name + ': ' + this.y ;
                });

                return label;
            },
            shared: true,
            shared: true,
            useHTML: true
        },
        plotOptions: {
            series: {
                    cursor: 'pointer',
                    point: {
                            events: {
                                click: function () {
                                    var firstDate = $('#firstDate').val();
                                    var lastDate = $('#lastDate').val();
                                    var type = $('#type').val();
                                    var where = "status = 'closed successful' AND closetime >= '" + firstDate + "' AND closetime <= '" + lastDate + "' AND service = '" + this.category + "'" ;
                                                 
                                    $.post( "ticketlist", 
                                            { where: where,
                                              type: type  } ).done(function( data ) {
                                        $('#logTicket').html(data);  
                                    });                                           
                                    $('#myModal').modal('show');
                                }
                            }
                        }
                },
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Ticket fechados',
            data: [ <?php echo $this->values; ?> ],
            dataLabels: {
                    enabled: true,
                    rotation: 0,
                    align: 'center',
                    x: 0,
                    y: 0,
                    style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif',
                        fontWeight: 'bold',
                        
                    }
            }

        },]
    });
  
</script>

<?php 
    else :
?>
<script type="text/javascript">
        
        $('#volumeService').html('<h3 align="center"><i>Não há dados para exibir o gráfico "Top 10 - Volume de tickets por serviços". Por favor, altere os filtros.</i></h3>');

</script>
<?php
    endif
?>

<!-- Scripts -->
  <?php echo $this->headScript()
  ->prependFile($this->basePath() . '/js/dropdown.js')  ; ?>